### ISSUE TITLE
Code review: using standard library / helper functions / DRY (Don't Repeat Yourself)

### ISSUE THREAD

**Issue by maks-a** [EKrysenko/homework#1]
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp1.java#L435-L439

Use something from standard library. If that's not allowed write your own implementation.
```java
return max(a, max(b, c));
```

**Comment by EKrysenko** [comment]
Oi, Math.max(a, b) fits, I suppose. Stupid me lol. Done.
