### ISSUE TITLE
Code review: complex conditionals, a < x < b order

### ISSUE THREAD

**Issue by maks-a** [EKrysenko/homework#2]
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp1.java#L101

Try using a < x < b form.
```java
return 13 <= a && a <= 19 || 
       13 <= b && b <= 19 || 
       13 <= c && c <= 19;
```
Or `isWithin(a, 13, 19)`.

Same story:
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp1.java#L155
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp1.java#L197

**Comment by EKrysenko** [comment]
Done.
