### ISSUE TITLE
Code review: ternary operator vs if-statements

### ISSUE THREAD

**Issue by maks-a** [EKrysenko/homework#3]
1) Instead of this:
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp1.java#L131-L137
consider that:
```java
if (aTo10 == bTo10) {
  return 0;
}
return aTo10 < bTo10 ? a : b;
```
2) Don't use if-return-else-return combo (with simple one-liner returns):
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp1.java#L377-L381
`else` makes no sense here.
Consider either:
```java
if (condition) {
  return something;
}
return other_thing;
```
or ternary operator:
```java
return condition ? something : other_thing;
```

**Comment by EKrysenko** [comment]
Done.
