### ISSUE TITLE
Code review: complex ternary operator

### ISSUE THREAD

**Issue by maks-a** [EKrysenko/homework#4]
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp1.java#L30
Consider breaking in lines a complex ternary operator:
```java
return condition
  ? something_complex
  : another_complex_stuff;
// for example:
return 21 < n   // rememeber: a < b (lower on the left)
  ? (n - 21) * 2
  : 21 - n; 
```
Same story:
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp1.java#L332
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/Logic1.java#L15

**Comment by EKrysenko** [comment]
I clean it up but should ask my training course leader about Java standards.
