### ISSUE TITLE
Code review: formatting

### ISSUE THREAD

**Issue by maks-a** [EKrysenko/homework#5]
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp1.java#L306-L307
Check alignments:
```java
        return isWithin(a, 30, 40) && isWithin(b, 30, 40) ||
               isWithin(a, 40, 50) && isWithin(b, 40, 50);
```

**Comment by EKrysenko** [comment]
Agree. Don't know how could I miss it. Done..
