### ISSUE TITLE
Code review: use standard swap if possible

### ISSUE THREAD

**Issue by maks-a** [EKrysenko/homework#6]
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp1.java#L451-L455
Consider standard swap() if possible:
```java
if (a < b) {
  swap(a, b);
}
```
Same here:
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp2.java#L190

**Comment by EKrysenko** [comment]
There's no standard method "swap" in Java _afaik_.
