### ISSUE TITLE
Code review: safe loop iterations

### ISSUE THREAD

**Issue by maks-a** [EKrysenko/homework#7]
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp2.java#L76

That is error-prone because of i-type. In case it's unsigned (has no negative values) it may have type underflow.

Consider using this:
```java
for (int i = 0; i + 2 < nums.length; ++i)
```

Same here:
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp2.java#L113
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp2.java#L195
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp2.java#L227

**Comment by EKrysenko** [comment]
Done.
