### ISSUE TITLE
Code review: min/max

### ISSUE THREAD

**Issue by maks-a** [EKrysenko/homework#8]
https://github.com/EKrysenko/homework/blob/4d09fd46b880f4fb2db6459dcae1c7b2193f9ac5/src/codingbat/WarmUp2.java#L281-L283

Those are equal:
```java
if (x < a) {
  a = x;
}
// and
a = min(a, x);
```
and this:
```java
if (a < x) {
  a = x;
}
// and
a = max(a, x);
```

**Comment by EKrysenko** [comment]
Done.
